# Production-specific configuration
# This file extends _config.yml for production builds

# Production URL (override for deployment)
url: "https://marcospaterson.github.io"

# Performance optimizations for production
sass:
  style: compressed
  sourcemap: never

# Additional optimizations
incremental: false
profile: false
strict_front_matter: true

# Analytics and tracking (uncomment when ready)
google_analytics: G-TRZ85JG6LN
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-TRZ85JG6LN"  # Same as above
    anonymize_ip: true

# Production-specific plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO and social sharing (optional future enhancements)
author:
  name: Marcos Paterson
  bio: Quant Developer and Tech Enthusiast
  email: marcos.paterson@gmail.com

social:
  name: Marcos Paterson
  links:
    - https://github.com/marcospaterson
    - https://linkedin.com/in/marcospaterson

# Additional exclusions for production
exclude:
  - README.md
  - DEPLOYMENT.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache
  - .jekyll-cache
  - .github/
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - deploy.sh
  - "*.swp"
  - "*.orig"
  - .DS_Store
  - Thumbs.db
